# edhrec_kuja.py - from EDHREC deckpreview: https://moxfield.com/decks/-fuwGWXwgEuicZoFLj2ZTQ
# Commander: Kuja, Genome Sorcerer
COMMANDER = "Kuja, Genome Sorcerer"
DECK = [
    ('Birgi, God of Storytelling', 3, 'creature', 0, 0, ['creature']),
    ('Braids, Arisen Nightmare', 3, 'creature', 0, 0, ['creature', 'draw']),
    ('Coruscation Mage', 2, 'creature', 0, 0, ['creature', 'token', 'burn']),
    ('Dauthi Voidwalker', 2, 'creature', 0, 0, ['creature']),
    ('Dualcaster Mage', 3, 'creature', 0, 0, ['creature']),
    ('Guttersnipe', 3, 'creature', 0, 0, ['creature', 'burn']),
    ('Harmonic Prodigy', 2, 'creature', 0, 0, ['creature']),
    ('Imperial Recruiter', 3, 'creature', 0, 0, ['creature']),
    ('Opposition Agent', 3, 'creature', 0, 0, ['creature']),
    ('Orcish Bowmasters', 2, 'creature', 0, 0, ['creature', 'draw', 'removal']),
    ('Ragavan, Nimble Pilferer', 1, 'creature', 0, 0, ['creature', 'token']),
    ('Roaming Throne', 4, 'creature', 0, 0, ['creature']),
    ('Sheoldred, the Apocalypse', 4, 'creature', 0, 0, ['creature', 'draw']),
    ('Simian Spirit Guide', 3, 'creature', 0, 0, ['creature']),
    ('Solphim, Mayhem Dominus', 4, 'creature', 0, 0, ['creature']),
    ('Storm-Kiln Artist', 4, 'creature', 0, 0, ['creature', 'token']),
    ('Urabrask', 4, 'creature', 0, 0, ['creature', 'removal']),
    ('Ad Nauseam', 5, 'spell', 0, 0, ['spell', 'is']),
    ('Cabal Ritual', 2, 'spell', 0, 0, ['spell', 'is']),
    ('Culling the Weak', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Dark Ritual', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Deadly Dispute', 2, 'spell', 0, 0, ['spell', 'draw', 'token', 'is']),
    ('Deadly Rollick', 4, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Deflecting Swat', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Desperate Ritual', 2, 'spell', 0, 0, ['spell', 'is']),
    ('Fire Covenant', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Flare of Duplication', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Force of Despair', 3, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Pyretic Ritual', 2, 'spell', 0, 0, ['spell', 'is']),
    ('Pyroblast', 1, 'spell', 0, 0, ['spell', 'counter', 'removal', 'is']),
    ('Pyrokinesis', 6, 'spell', 0, 0, ['spell', 'is']),
    ('Red Elemental Blast', 1, 'spell', 0, 0, ['spell', 'counter', 'removal', 'is']),
    ('Reiterate', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Saw in Half', 3, 'spell', 0, 0, ['spell', 'removal', 'token', 'is']),
    ('Seething Song', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Slaughter Pact', 0, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Snuff Out', 4, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Vampiric Tutor', 1, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ("Wyll's Reversal", 3, 'spell', 0, 0, ['spell', 'is']),
    ('Bonus Round', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Chain of Smog', 2, 'spell', 0, 0, ['spell', 'is']),
    ('Demonic Tutor', 2, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Diabolic Intent', 2, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Faithless Looting', 1, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Gamble', 1, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Grapeshot', 2, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Imperial Seal', 1, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ("Jeska's Will", 3, 'spell', 0, 0, ['spell', 'is']),
    ('Rite of Flame', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Twinflame', 2, 'spell', 0, 0, ['spell', 'token', 'is']),
    ('Vandalblast', 1, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ("Yawgmoth's Will", 3, 'spell', 0, 0, ['spell', 'is']),
    ('Aetherflux Reservoir', 4, 'spell', 0, 0, ['spell', 'removal']),
    ('Arcane Signet', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Chrome Mox', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Defense Grid', 2, 'spell', 0, 0, ['spell']),
    ('Lightning Greaves', 2, 'spell', 0, 0, ['spell']),
    ('Lotus Bloom', 0, 'spell', 0, 0, ['spell']),
    ('Lotus Petal', 0, 'spell', 0, 0, ['spell']),
    ('Mana Vault', 1, 'spell', 0, 0, ['spell', 'rock', 'ramp', 'draw']),
    ('Mox Amber', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Mox Opal', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Rakdos Signet', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Ruby Medallion', 2, 'spell', 0, 0, ['spell']),
    ('Sol Ring', 1, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Talisman of Indulgence', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('The One Ring', 4, 'spell', 0, 0, ['spell', 'draw']),
    ('Wishclaw Talisman', 2, 'spell', 0, 0, ['spell', 'tutor']),
    ('Blood Moon', 3, 'spell', 0, 0, ['spell']),
    ('Bloodchief Ascension', 1, 'spell', 0, 0, ['spell']),
    ('Necropotence', 3, 'spell', 0, 0, ['spell', 'draw']),
    ('Underworld Breach', 2, 'spell', 0, 0, ['spell']),
    ('Ancient Tomb', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Arid Mesa', 0, 'land', 0, 0, ['land']),
    ('Blazemire Verge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Blood Crypt', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Bloodstained Mire', 0, 'land', 0, 0, ['land']),
    ('City of Brass', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Command Tower', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Foreboding Ruins', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Gemstone Caverns', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Lindblum, Industrial Regency', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Luxury Suite', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Mana Confluence', 0, 'land', 0, 0, ['land']),
    ('Marsh Flats', 0, 'land', 0, 0, ['land']),
    ('Mountain', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Mountain', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Phyrexian Tower', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Polluted Delta', 0, 'land', 0, 0, ['land']),
    ('Prismatic Vista', 0, 'land', 0, 0, ['land', 'ramp']),
    ('Scalding Tarn', 0, 'land', 0, 0, ['land']),
    ('Swamp', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Swamp', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Swamp', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Swamp', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Swamp', 0, 'land', 0, 0, ['land', 'manaland']),
    ("Urza's Saga", 0, 'land', 0, 0, ['land', 'manaland', 'draw', 'token']),
    ('Verdant Catacombs', 0, 'land', 0, 0, ['land']),
    ('Wooded Foothills', 0, 'land', 0, 0, ['land']),
]
