# edhrec_nekusar.py - from EDHREC deckpreview: https://moxfield.com/decks/6TkNHgp1TUuaK3rfgvjrSw
# Commander: Nekusar, the Mindrazer
COMMANDER = "Nekusar, the Mindrazer"
DECK = [
    ('Barbed Shocker', 4, 'creature', 0, 0, ['creature', 'draw']),
    ('Boggart Trawler', 3, 'creature', 0, 0, ['creature', 'removal']),
    ('Braids, Arisen Nightmare', 3, 'creature', 0, 0, ['creature', 'draw']),
    ('Consecrated Sphinx', 6, 'creature', 0, 0, ['creature', 'draw']),
    ('Faerie Mastermind', 2, 'creature', 0, 0, ['creature', 'draw']),
    ('Hullbreaker Horror', 7, 'creature', 0, 0, ['creature']),
    ('Hydroelectric Specimen', 3, 'creature', 0, 0, ['creature']),
    ('Jin-Gitaxias, Core Augur', 10, 'creature', 0, 0, ['creature', 'draw']),
    ('Jin-Gitaxias, Progress Tyrant', 7, 'creature', 0, 0, ['creature']),
    ('Malcolm, Alluring Scoundrel', 2, 'creature', 0, 0, ['creature', 'draw']),
    ('Niv-Mizzet, Parun', 6, 'creature', 0, 0, ['creature', 'draw', 'removal']),
    ('Orcish Bowmasters', 2, 'creature', 0, 0, ['creature', 'draw', 'removal']),
    ('Platinum Angel', 7, 'creature', 0, 0, ['creature']),
    ('Sheoldred, the Apocalypse', 4, 'creature', 0, 0, ['creature', 'draw']),
    ('Sire of Insanity', 6, 'creature', 0, 0, ['creature']),
    ('Talion, the Kindly Lord', 4, 'creature', 0, 0, ['creature', 'draw']),
    ('Tinybones, Bauble Burglar', 2, 'creature', 0, 0, ['creature']),
    ('Tinybones, Trinket Thief', 2, 'creature', 0, 0, ['creature', 'draw']),
    ('Urza, Lord High Artificer', 4, 'creature', 0, 0, ['creature', 'token']),
    ('Cabal Ritual', 2, 'spell', 0, 0, ['spell', 'is']),
    ('Commandeer', 7, 'spell', 0, 0, ['spell', 'is']),
    ('Entomb', 1, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Fell the Profane', 4, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Malakir Rebirth', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Mana Drain', 2, 'spell', 0, 0, ['spell', 'counter', 'is']),
    ('Muddle the Mixture', 2, 'spell', 0, 0, ['spell', 'counter', 'tutor', 'is']),
    ('Mystical Tutor', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Sink into Stupor', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Vampiric Tutor', 1, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Wheel and Deal', 4, 'spell', 0, 0, ['spell', 'draw', 'wheel', 'is']),
    ('Dark Deal', 3, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Demonic Tutor', 2, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Enter the Infinite', 12, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Molten Psyche', 3, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Peer into the Abyss', 7, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Reanimate', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Show and Tell', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Wheel of Fortune', 3, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Wheel of Misfortune', 3, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Whispering Madness', 4, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Windfall', 3, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Arcane Signet', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Chalice of the Void', 1, 'spell', 0, 0, ['spell']),
    ('Chrome Mox', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Fellwar Stone', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Howling Mine', 2, 'spell', 0, 0, ['spell', 'draw']),
    ('Lotus Petal', 0, 'spell', 0, 0, ['spell']),
    ('Meekstone', 1, 'spell', 0, 0, ['spell']),
    ('Mindslaver', 6, 'spell', 0, 0, ['spell']),
    ('Mox Amber', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Mox Diamond', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Mox Opal', 0, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Sol Ring', 1, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Static Orb', 3, 'spell', 0, 0, ['spell']),
    ('Talisman of Creativity', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Talisman of Dominance', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ("Teferi's Puzzle Box", 4, 'spell', 0, 0, ['spell', 'draw']),
    ('The One Ring', 4, 'spell', 0, 0, ['spell', 'draw']),
    ('Trinisphere', 3, 'spell', 0, 0, ['spell']),
    ('Unwinding Clock', 4, 'spell', 0, 0, ['spell']),
    ('Vedalken Orrery', 4, 'spell', 0, 0, ['spell']),
    ('Winter Orb', 2, 'spell', 0, 0, ['spell']),
    ('Animate Dead', 2, 'spell', 0, 0, ['spell']),
    ('Arcane Laboratory', 3, 'spell', 0, 0, ['spell']),
    ('Copy Artifact', 2, 'spell', 0, 0, ['spell']),
    ('Copy Enchantment', 3, 'spell', 0, 0, ['spell']),
    ('Curiosity', 1, 'spell', 0, 0, ['spell', 'draw']),
    ("Liliana's Caress", 2, 'spell', 0, 0, ['spell']),
    ('Omniscience', 10, 'spell', 0, 0, ['spell']),
    ('Rhystic Study', 3, 'spell', 0, 0, ['spell', 'draw']),
    ('Stasis', 2, 'spell', 0, 0, ['spell']),
    ('Underworld Breach', 2, 'spell', 0, 0, ['spell']),
    ('Dack Fayden', 3, 'spell', 0, 0, ['spell', 'draw']),
    ('Narset, Parter of Veils', 3, 'spell', 0, 0, ['spell', 'draw']),
    ('Tezzeret, Master of the Bridge', 6, 'spell', 0, 0, ['spell']),
    ('Blood Crypt', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Bloodstained Mire', 0, 'land', 0, 0, ['land']),
    ('Cabal Coffers', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Cavern of Souls', 0, 'land', 0, 0, ['land', 'manaland']),
    ('City of Brass', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Command Tower', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Exotic Orchard', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Great Furnace', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Mana Confluence', 0, 'land', 0, 0, ['land']),
    ('Mistrise Village', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Polluted Delta', 0, 'land', 0, 0, ['land']),
    ('Raucous Theater', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Scalding Tarn', 0, 'land', 0, 0, ['land']),
    ('Seat of the Synod', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Shivan Reef', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Steam Vents', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Sulfurous Springs', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Thundering Falls', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Undercity Sewers', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Underground River', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Urborg, Tomb of Yawgmoth', 0, 'land', 0, 0, ['land']),
    ('Vault of Whispers', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Vesuva', 0, 'land', 0, 0, ['land']),
    ('Watery Grave', 0, 'land', 0, 0, ['land', 'manaland']),
]
