# deck_v12.py - Ovika "Convoke Engine" v12.1 FINAL (adopted build)
# Commander: Ovika, Enigma Goliath
# Strategy: noncreature spells make X goblins (X=MV) with Ovika; goblins
# convoke-pay the next spells; City on Fire / Collective Inferno / Torbran
# amplify damage. Pod-verified: 9/36 wins (25%) on the fixed engine.
# v12.2 (Guttersnipe/Coruscation/Seething Song) measured 8/36 -> not adopted.
COMMANDER = "Ovika, Enigma Goliath"
DECK = [
    # --- Lands (28) ---
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Island", 0, "land", 0, 0, ["basic", "u", "island"]),
    ("Island", 0, "land", 0, 0, ["basic", "u", "island"]),
    ("Island", 0, "land", 0, 0, ["basic", "u", "island"]),
    ("Island", 0, "land", 0, 0, ["basic", "u", "island"]),
    ("Island", 0, "land", 0, 0, ["basic", "u", "island"]),
    ("Command Tower", 0, "land", 0, 0, ["any"]),
    ("Exotic Orchard", 0, "land", 0, 0, ["any"]),
    ("Path of Ancestry", 0, "land", 0, 0, ["any"]),
    ("Swiftwater Cliffs", 0, "land", 0, 0, ["u", "r"]),
    ("Shivan Reef", 0, "land", 0, 0, ["u", "r"]),
    ("Myriad Landscape", 0, "land", 0, 0, ["myriad"]),
    ("Terramorphic Expanse", 0, "land", 0, 0, ["fetcher"]),
    ("Cascading Cataracts", 0, "land", 0, 0, ["cataracts"]),
    ("Power Depot", 0, "land", 0, 0, ["any"]),
    ("Kher Keep", 0, "land", 0, 0, ["goblin", "token"]),
    ("Spire of Industry", 0, "land", 0, 0, ["any"]),
    ("Sulfur Falls", 0, "land", 0, 0, ["u", "r"]),
    ("Stormcarved Coast", 0, "land", 0, 0, ["u", "r"]),
    ("Spirebluff Canal", 0, "land", 0, 0, ["u", "r"]),
    ("Steam Vents", 0, "land", 0, 0, ["u", "r"]),
    ("Cascade Bluffs", 0, "land", 0, 0, ["u", "r"]),
    ("Sokenzan, Crucible of Defiance", 0, "land", 0, 0, ["r"]),
    ("Fiery Islet", 0, "land", 0, 0, ["u", "r"]),
    # --- Ramp (11) ---
    ("Sol Ring", 1, "spell", 0, 0, ["ramp", "rock", "+2"]),
    ("Arcane Signet", 2, "spell", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("Fellwar Stone", 2, "spell", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("Mind Stone", 2, "spell", 0, 0, ["ramp", "rock", "+1"]),
    ("Talisman of Creativity", 2, "spell", 0, 0, ["ramp", "rock", "+1"]),
    ("Commander's Sphere", 3, "spell", 0, 0, ["ramp", "rock", "+1", "sphere"]),
    ("Wayfarer's Bauble", 1, "spell", 0, 0, ["ramp", "bauble"]),
    ("Everflowing Chalice", 2, "spell", 0, 0, ["ramp", "rock", "+2"]),
    ("Chromatic Lantern", 3, "spell", 0, 0, ["ramp", "rock", "+1", "anycolor", "lantern"]),
    ("Thran Dynamo", 4, "spell", 0, 0, ["ramp", "rock", "+3"]),
    ("Worn Powerstone", 3, "spell", 0, 0, ["ramp", "rock", "+2"]),
    # --- Draw engines (12) ---
    ("Rhystic Study", 3, "spell", 1, 0, ["rhystic"]),
    ("Mystic Remora", 1, "spell", 1, 0, ["remora"]),
    ("Skullclamp", 1, "spell", 0, 0, ["clamp"]),
    ("Fact or Fiction", 4, "spell", 2, 0, ["draw4", "is"]),
    ("Frantic Search", 3, "spell", 2, 0, ["frantic", "is"]),
    ("Recurring Insight", 6, "spell", 2, 0, ["recurring", "is"]),
    ("Windfall", 3, "spell", 1, 0, ["windfall", "is"]),
    ("Past in Flames", 3, "spell", 0, 2, ["past", "is"]),
    ("The One Ring", 4, "spell", 0, 0, ["ring"]),
    ("Treasure Cruise", 8, "spell", 1, 0, ["cruise", "is"]),
    # --- Convoke payoffs (12) ---
    ("Stoke the Flames", 4, "spell", 0, 0, ["convoke", "burn", "is"]),
    ("Temporal Cleansing", 4, "spell", 1, 0, ["convoke", "removal", "is"]),
    ("Meeting of Minds", 4, "spell", 1, 0, ["convoke", "draw2", "is"]),
    ("Unexpected Assistance", 5, "spell", 2, 0, ["convoke", "draw3", "is"]),
    ("Artistic Refusal", 6, "spell", 2, 0, ["convoke", "counter", "draw2", "is"]),
    ("Complete the Circuit", 6, "spell", 1, 0, ["convoke", "big", "circuit", "is"]),
    ("Harmonized Crescendo", 6, "spell", 2, 0, ["convoke", "draw", "is"]),
    ("Transcendent Message", 5, "spell", 4, 0, ["xspell", "convoke", "message", "is"]),
    ("Calamity of Cinders", 7, "spell", 0, 0, ["convoke", "removal", "is"]),
    ("City on Fire", 8, "spell", 0, 0, ["convoke", "big", "damage"]),
    ("Collective Inferno", 5, "spell", 0, 0, ["convoke", "damage"]),
    ("Obelisk of Urd", 6, "spell", 0, 0, ["convoke", "anthem"]),
    # --- Creatures / convoke bodies (16) ---
    ("Zephyr Singer", 4, "creature", 2, 0, ["convoke", "body", "flying"]),
    ("Will-Forged Golem", 6, "creature", 0, 0, ["convoke", "body"]),
    ("Thunderhead Squadron", 6, "creature", 1, 0, ["convoke", "body", "flying"]),
    ("Interdisciplinary Mascot", 8, "creature", 2, 0, ["convoke", "body"]),
    ("Joyful Stormsculptor", 4, "creature", 1, 1, ["body", "token", "convoke"]),
    ("Chief Engineer", 2, "creature", 1, 0, ["convoke", "body"]),
    ("Mogg War Marshal", 2, "creature", 0, 1, ["body2", "goblin"]),
    ("Siege-Gang Commander", 5, "creature", 0, 3, ["body3", "goblin"]),
    ("Goblin Rabblemaster", 3, "creature", 0, 2, ["rabble"]),
    ("Krenko, Mob Boss", 4, "creature", 0, 2, ["krenko"]),
    ("Skirk Prospector", 1, "creature", 0, 1, ["skirk"]),
    ("Goblin Warchief", 3, "creature", 0, 2, ["warchief", "goblin"]),
    ("Veyran, Voice of Duality", 3, "creature", 1, 1, ["veyran"]),
    ("Roaming Throne", 4, "creature", 0, 0, ["throne"]),
    ("Storm-Kiln Artist", 4, "creature", 0, 3, ["stormkiln"]),
    ("Torbran, Thane of Red Fell", 4, "creature", 0, 3, ["damage", "torbran"]),
    # --- Token spells (6) ---
    ("Krenko's Command", 2, "spell", 0, 1, ["body2", "is"]),
    ("Dragon Fodder", 2, "spell", 0, 1, ["body2", "is"]),
    ("Hordeling Outburst", 3, "spell", 0, 2, ["body3", "goblin", "is"]),
    ("Goblin Assault", 3, "spell", 0, 2, ["assault"]),
    ("Empty the Warrens", 4, "spell", 0, 2, ["warrens", "goblin", "is"]),
    ("Song of Totentanz", 1, "spell", 0, 1, ["big", "song", "xspell", "is"]),
    # --- Burst engines / velocity ---
    ("Mana Echoes", 3, "spell", 0, 0, ["echoes"]),
    ("Mana Geyser", 5, "spell", 0, 2, ["big", "geyser", "is"]),
    ("Brightstone Ritual", 1, "spell", 0, 1, ["big", "brightstone", "is"]),
    ("Battle Hymn", 2, "spell", 0, 1, ["hymn", "is"]),
    ("Consider", 1, "spell", 1, 0, ["draw1", "is"]),
    ("Opt", 1, "spell", 1, 0, ["draw1", "is"]),
    ("Preordain", 1, "spell", 1, 0, ["draw1", "is"]),
    ("Thought Scour", 1, "spell", 1, 0, ["draw1", "is"]),
    # --- Protection (9) ---
    ("Counterspell", 2, "spell", 2, 0, ["counter", "is"]),
    ("An Offer You Can't Refuse", 1, "spell", 1, 0, ["counter", "is"]),
    ("Fierce Guardianship", 3, "spell", 1, 0, ["counter", "is"]),
    ("Spell Pierce", 1, "spell", 1, 0, ["counter", "is"]),
    ("Mana Drain", 2, "spell", 2, 0, ["counter", "is"]),
    # --- Utility / finishers (6) ---
    ("Lightning Greaves", 2, "spell", 0, 0, ["greaves"]),
    ("Shark Typhoon", 6, "spell", 1, 0, ["shark"]),
    ("Jeska's Will", 3, "spell", 0, 2, ["jeskas", "is"]),
]
