# deck_v1.py - baseline Ovika deck built from collection (heuristic baseline per skill v3)
# Fields: name, mv (as-cast mana value), kind: land|creature|spell, u/r = colored pips needed, tags

DECK = [
    # --- Lands (25) ---
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Mountain", 0, "land", 0, 0, ["basic", "r", "mountain"]),
    ("Command Tower", 0, "land", 0, 0, ["any"]),
    ("Exotic Orchard", 0, "land", 0, 0, ["any"]),
    ("Path of Ancestry", 0, "land", 0, 0, ["any"]),
    ("Baron, Airship Kingdom", 0, "land", 0, 0, ["u", "r"]),
    ("Peculiar Lighthouse", 0, "land", 0, 0, ["u", "r"]),
    ("Jidoor, Aristocratic Capital // Overture", 0, "land", 0, 0, ["u", "town"]),
    ("Crossroads Village", 0, "land", 0, 0, ["u", "r", "town"]),
    ("Command Bridge", 0, "land", 0, 0, ["any"]),
    ("Cascading Cataracts", 0, "land", 0, 0, ["cataracts"]),
    ("Power Depot", 0, "land", 0, 0, ["any"]),
    ("Terramorphic Expanse", 0, "land", 0, 0, ["fetcher"]),
    ("The Autonomous Furnace", 0, "land", 0, 0, ["r"]),
    ("The Monumental Facade", 0, "land", 0, 0, []),
    ("Adventurer's Inn", 0, "land", 0, 0, ["town"]),
    ("Eden, Seat of the Sanctum", 0, "land", 0, 0, []),
    ("Animal Sanctuary", 0, "land", 0, 0, []),
    ("Inventors' Fair", 0, "land", 0, 0, []),
    ("Mirrorpool", 0, "land", 0, 0, []),
    ("Mystifying Maze", 0, "land", 0, 0, []),
    ("Terrain Generator", 0, "land", 0, 0, ["terrain"]),
    # --- Ramp (12) ---
    ("Sol Ring", 1, "spell", 0, 0, ["ramp", "rock", "+2"]),
    ("Arcane Signet", 2, "spell", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("Everflowing Chalice", 2, "spell", 0, 0, ["ramp", "rock", "+2"]),
    ("Pristine Talisman", 3, "spell", 0, 0, ["ramp", "rock", "+1", "life"]),
    ("Phyrexian Atlas", 3, "spell", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("The Eternity Elevator", 5, "spell", 0, 0, ["ramp", "rock", "+3"]),
    ("Burnished Hart", 3, "creature", 0, 0, ["ramp", "hart"]),
    ("PuPu UFO", 2, "creature", 0, 0, ["ramp", "pupu"]),
    ("Three Tree Mascot", 2, "creature", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("Myr Convert", 2, "creature", 0, 0, ["ramp", "rock", "+1", "anycolor"]),
    ("Koth, Fire of Resistance", 4, "spell", 0, 2, ["ramp", "koth"]),
    ("The Fire Crystal", 4, "spell", 0, 2, ["redcost", "firecrystal"]),
    # --- Draw (14) ---
    ("Skullclamp", 1, "spell", 0, 0, ["clamp"]),
    ("Think Twice", 2, "spell", 1, 0, ["draw1", "is"]),
    ("Thrill of Possibility", 2, "spell", 0, 1, ["draw2", "is"]),
    ("Grab the Prize", 2, "spell", 0, 1, ["draw2", "is"]),
    ("Light Up the Stage", 3, "spell", 0, 2, ["draw2", "is"]),
    ("Lunar Insight", 3, "spell", 2, 0, ["draw", "lunar", "is"]),
    ("Marina Vendrell's Grimoire", 6, "spell", 1, 0, ["draw", "5", "grimoire"]),
    ("Travel the Overworld", 7, "spell", 2, 0, ["draw", "4", "travel", "towns"]),
    ("Vivisurgeon's Insight", 5, "spell", 2, 0, ["draw3", "is"]),
    ("Unfathomable Truths", 5, "spell", 1, 0, ["draw", "3", "body"]),
    ("Focus the Mind", 5, "spell", 1, 0, ["draw", "3", "focus"]),
    ("Cerebral Download", 5, "spell", 1, 0, ["draw3", "is"]),
    ("Glimmerburst", 4, "spell", 1, 0, ["draw", "2", "body"]),
    ("Roiling Dragonstorm", 2, "spell", 1, 0, ["draw2", "is"]),
    # --- Interaction (11) ---
    ("Cryptic Command", 4, "spell", 3, 0, ["counter", "draw1"]),
    ("An Offer You Can't Refuse", 1, "spell", 1, 0, ["counter"]),
    ("Syncopate", 1, "spell", 1, 0, ["counter"]),
    ("Deny the Divine", 3, "spell", 1, 0, ["counter"]),
    ("Untimely Malfunction", 2, "spell", 0, 1, ["counter"]),
    ("Abrade", 2, "spell", 0, 1, ["removal"]),
    ("Lightning Bolt", 1, "spell", 0, 1, ["removal"]),
    ("Burst Lightning", 1, "spell", 0, 1, ["removal"]),
    ("Scorching Dragonfire", 2, "spell", 0, 1, ["removal"]),
    ("Eject", 4, "spell", 1, 0, ["counter", "draw1"]),
    ("Aetherize", 4, "spell", 2, 0, ["defense"]),
    # --- Engines / creatures (15) ---
    ("Tellah, Great Sage", 5, "creature", 1, 1, ["tellah"]),
    ("Goblin Rabblemaster", 3, "creature", 0, 2, ["rabble"]),
    ("Shock Brigade", 2, "creature", 0, 1, ["mobilize"]),
    ("Chimney Rabble", 4, "creature", 0, 3, ["body2"]),
    ("Heroes of the Revel", 5, "creature", 0, 4, ["body2"]),
    ("Thryx, the Sudden Storm", 5, "creature", 2, 0, ["thryx"]),
    ("Shantotto, Tactician Magician", 3, "creature", 1, 1, ["shantotto"]),
    ("Trinket Mage", 3, "creature", 2, 0, ["trinket"]),
    ("Micromancer", 4, "creature", 2, 0, ["micromancer"]),
    ("Urabrask's Forge", 3, "spell", 0, 2, ["forge"]),
    ("Urabrask the Hidden", 5, "creature", 0, 3, ["body"]),
    ("Ultros, Obnoxious Octopus", 2, "creature", 1, 0, ["ultros"]),
    # --- Big payoffs (10) ---
    ("Sea God's Scorn", 6, "spell", 2, 0, ["big"]),
    ("Pinnacle Kill-Ship", 7, "spell", 0, 0, ["big", "body"]),
    ("Random Encounter", 6, "spell", 0, 2, ["big", "random"]),
    ("Breaching Dragonstorm", 5, "spell", 0, 4, ["big", "breach"]),
    ("Triple Triad", 6, "spell", 0, 3, ["big", "triad"]),
    ("Purphoros's Intervention", 1, "spell", 0, 1, ["big", "purphoros", "xspell"]),
    ("Relm's Sketching", 4, "spell", 2, 0, ["big", "copybody"]),
    ("Molten Rebuke", 5, "spell", 0, 4, ["big", "removal"]),
    ("Ashiok's Erasure", 4, "spell", 2, 0, ["big", "counter"]),
    ("Court of Vantress", 4, "spell", 2, 0, ["big"]),
    # --- Rooms (5) ---
    ("Smoky Lounge // Misty Salon", 3, "spell", 0, 2, ["room", "smoky"]),
    ("Meat Locker // Drowned Diner", 3, "spell", 2, 0, ["room", "meat"]),
    ("Ticket Booth // Tunnel of Hate", 3, "spell", 0, 2, ["room", "ticket"]),
    ("Glassworks // Shattered Yard", 3, "spell", 0, 2, ["room", "glass"]),
    ("Central Elevator // Promising Stairs", 4, "spell", 2, 0, ["room", "elevator"]),
    # --- Misc (13) ---
    ("Vexing Bauble", 1, "spell", 0, 0, ["draw", "1", "sacdraw"]),
    ("Dirgur Island Dragon // Skimming Strike", 2, "spell", 1, 0, ["draw1", "is"]),
    ("Don't Make a Sound", 2, "spell", 1, 0, ["counter"]),
    ("Refute", 3, "spell", 2, 0, ["counter", "draw1"]),
    ("Pearl of Wisdom", 3, "spell", 2, 0, ["draw2", "is"]),
    ("Combat Tutorial", 3, "spell", 2, 0, ["draw", "2", "body"]),
    ("Witness Protection", 1, "spell", 1, 0, ["removal"]),
    ("Surgical Skullbomb", 1, "spell", 0, 0, ["draw", "1", "sacdraw"]),
    ("Impact Tremors", 2, "spell", 0, 1, []),
    ("Satyr's Cunning", 1, "spell", 0, 1, ["body"]),
]

def check_deck(deck):
    from collections import Counter
    cnt = Counter(n for n, *_ in deck)
    dups = {k: v for k, v in cnt.items() if v > 1 and k != "Mountain"}
    print("total:", len(deck), "dups:", dups)

if __name__ == "__main__":
    check_deck(DECK)