# deck_terra.py - Terra, Magical Adept (WUBRG Final Fantasy enchantress)
# working = user (same engine as v1; candidate experiments apply here)'s submitted list, legalized:
#   - removed 2nd An Offer You Can't Refuse and 2nd Counterspell (singleton)
#   - added Rhystic Study (draw engine) and Arid Mesa (5c fixing)
# 99 main + commander = 100. Commander identity: WUBRG (both faces).
COMMANDER = "Terra, Magical Adept // Esper Terra"
DECK = [
    # --- Lands (33) ---
    ("Ancient Tomb", 0, "land", 0, 0, ["land", "ramp"]),
    ("Arid Mesa", 0, "land", 0, 0, ["land", "fetcher"]),
    ("Breeding Pool", 0, "land", 0, 0, ["land", "g", "u"]),
    ("Canopy Vista", 0, "land", 0, 0, ["land", "g", "w"]),
    ("Cinder Glade", 0, "land", 0, 0, ["land", "g", "r"]),
    ("Command Tower", 0, "land", 0, 0, ["land", "any"]),
    ("Exotic Orchard", 0, "land", 0, 0, ["land", "any"]),
    ("Forest", 0, "land", 0, 0, ["land", "basic", "g"]),
    ("Godless Shrine", 0, "land", 0, 0, ["land", "w", "b"]),
    ("Island", 0, "land", 0, 0, ["land", "basic", "u"]),
    ("Island", 0, "land", 0, 0, ["land", "basic", "u"]),
    ("Mountain", 0, "land", 0, 0, ["land", "basic", "r"]),
    ("Forest", 0, "land", 0, 0, ["land", "basic", "g"]),
    ("Misty Rainforest", 0, "land", 0, 0, ["land", "fetcher"]),
    ("Marsh Flats", 0, "land", 0, 0, ["land", "fetcher"]),
    ("Mountain", 0, "land", 0, 0, ["land", "basic", "r"]),
    ("Mountain", 0, "land", 0, 0, ["land", "basic", "r"]),
    ("Plains", 0, "land", 0, 0, ["land", "basic", "w"]),
    ("Plains", 0, "land", 0, 0, ["land", "basic", "w"]),
    ("Plateau", 0, "land", 0, 0, ["land", "w", "r"]),
    ("Savannah", 0, "land", 0, 0, ["land", "g", "w"]),
    ("Scattered Groves", 0, "land", 0, 0, ["land", "g", "w"]),
    ("Seachrome Coast", 0, "land", 0, 0, ["land", "w", "u"]),
    ("Shadowy Backstreet", 0, "land", 0, 0, ["land", "b", "w"]),
    ("Stomping Ground", 0, "land", 0, 0, ["land", "r", "g"]),
    ("Swamp", 0, "land", 0, 0, ["land", "basic", "b"]),
    ("Swamp", 0, "land", 0, 0, ["land", "basic", "b"]),
    ("Taiga", 0, "land", 0, 0, ["land", "r", "g"]),
    ("Tainted Wood", 0, "land", 0, 0, ["land", "b", "g"]),
    ("Temple Garden", 0, "land", 0, 0, ["land", "g", "w"]),
    ("Watery Grave", 0, "land", 0, 0, ["land", "u", "b"]),
    ("Windswept Heath", 0, "land", 0, 0, ["land", "fetcher"]),
    ("Wooded Foothills", 0, "land", 0, 0, ["land", "fetcher"]),
    # --- Ramp / dorks (11) ---
    ("Lotus Petal", 0, "spell", 0, 0, ["ramp", "rock"]),
    ("Sol Ring", 1, "spell", 0, 0, ["ramp", "rock"]),
    ("Arcane Signet", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Fellwar Stone", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Talisman of Conviction", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Talisman of Creativity", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Talisman of Dominance", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Talisman of Indulgence", 2, "spell", 0, 0, ["ramp", "rock"]),
    ("Birds of Paradise", 1, "creature", 0, 0, ["ramp", "dork"]),
    ("Citanul Stalwart", 1, "creature", 0, 0, ["ramp", "dork"]),
    ("Llanowar Elves", 1, "creature", 0, 0, ["ramp", "dork"]),
    ("Sanctum Weaver", 2, "creature", 0, 0, ["ramp", "engine"]),
    ("Dryad of the Ilysian Grove", 3, "creature", 0, 0, ["ramp"]),
    ("Enduring Vitality", 3, "creature", 0, 0, ["ramp"]),
    ("Farseek", 2, "spell", 0, 0, ["ramp"]),
    ("Nature's Lore", 2, "spell", 0, 0, ["ramp"]),
    ("Three Visits", 2, "spell", 0, 0, ["ramp"]),
    ("Land Tax", 1, "spell", 0, 0, ["ramp"]),
    # --- Draw engines (8) ---
    ("Rhystic Study", 3, "spell", 0, 0, ["draw"]),
    ("Sylvan Library", 2, "spell", 0, 0, ["draw"]),
    ("Esper Sentinel", 1, "creature", 0, 0, ["draw"]),
    ("Sythis, Harvest's Hand", 2, "creature", 0, 0, ["draw", "engine"]),
    ("Mesa Enchantress", 3, "creature", 0, 0, ["draw", "engine"]),
    ("Verduran Enchantress", 3, "creature", 0, 0, ["draw", "engine"]),
    ("Enchantress's Presence", 3, "spell", 0, 0, ["draw", "engine"]),
    ("Eidolon of Blossoms", 4, "creature", 0, 0, ["draw", "engine"]),
    ("Setessan Champion", 3, "creature", 0, 0, ["draw", "engine"]),
    ("Smothering Tithe", 4, "spell", 0, 0, ["ramp", "engine"]),
    # --- Engine / payoffs (14) ---
    ("Six", 3, "creature", 0, 0, ["engine"]),
    ("The Master of Keys", 3, "creature", 0, 0, ["engine"]),
    ("Ponder", 1, "spell", 0, 0, ["draw"]),
    ("Archon of Sun's Grace", 4, "creature", 0, 0, ["engine", "token"]),
    ("Spark Double", 4, "creature", 0, 0, ["engine"]),
    ("Yenna, Redtooth Regent", 4, "creature", 0, 0, ["engine"]),
    ("Brainstorm", 1, "spell", 0, 0, ["draw"]),
    ("Demon of Fate's Design", 6, "creature", 0, 0, ["engine"]),
    ("Delighted Halfling", 1, "creature", 0, 0, ["ramp", "dork"]),
    ("Mirrormade", 3, "spell", 0, 0, ["engine"]),
    ("Binding the Old Gods", 4, "spell", 0, 0, ["engine"]),
    ("Opalescence", 4, "spell", 0, 0, ["engine"]),
    ("The Apprentice's Folly", 4, "spell", 0, 0, ["engine"]),
    ("Enchanted Evening", 5, "spell", 0, 0, ["engine"]),
    ("Starfield of Nyx", 5, "spell", 0, 0, ["engine"]),
    ("Estrid's Invocation", 3, "spell", 0, 0, ["engine"]),
    ("Moonmist", 2, "spell", 0, 0, []),
    # --- Interaction (13) ---
    ("An Offer You Can't Refuse", 1, "spell", 0, 0, ["counter"]),
    ("Counterspell", 2, "spell", 0, 0, ["counter"]),
    ("Path to Exile", 1, "spell", 0, 0, ["removal"]),
    ("Swords to Plowshares", 1, "spell", 0, 0, ["removal"]),
    ("Assassin's Trophy", 2, "spell", 0, 0, ["removal"]),
    ("Archdruid's Charm", 3, "spell", 0, 0, ["removal"]),
    ("Amphibian Downpour", 3, "spell", 0, 0, ["removal"]),
    ("Culling Ritual", 4, "spell", 0, 0, ["mass"]),
    ("Heroic Intervention", 2, "spell", 0, 0, ["protect"]),
    ("Destiny Spinner", 2, "creature", 0, 0, ["protect"]),
    ("Grand Abolisher", 2, "creature", 0, 0, ["protect"]),
    ("Preordain", 1, "spell", 0, 0, ["draw"]),
    # --- Tutors / graveyard (11) ---
    ("Enlightened Tutor", 1, "spell", 0, 0, ["tutor"]),
    ("Entomb", 1, "spell", 0, 0, ["tutor"]),
    ("Demonic Counsel", 2, "spell", 0, 0, ["tutor"]),
    ("Idyllic Tutor", 3, "spell", 0, 0, ["tutor"]),
    ("Neoform", 2, "spell", 0, 0, ["tutor"]),
    ("Eldritch Evolution", 3, "spell", 0, 0, ["tutor"]),
    ("Dark Ritual", 1, "spell", 0, 0, ["ritual"]),
    ("Reanimate", 1, "spell", 0, 0, ["reanimate"]),
    ("Sevinne's Reclamation", 3, "spell", 0, 0, ["reanimate"]),
]

