# edhrec_minstrel.py - from EDHREC deckpreview: https://archidekt.com/decks/22603494
# Commander: The Wandering Minstrel
COMMANDER = "The Wandering Minstrel"
DECK = [
    ('Avatar Kyoshi, Earthbender', 8, 'creature', 0, 0, ['creature']),
    ('Azusa, Lost but Seeking', 3, 'creature', 0, 0, ['creature']),
    ('Bumi, Unleashed', 5, 'creature', 0, 0, ['creature', 'mass']),
    ('Earthen Ally', 1, 'creature', 0, 0, ['creature']),
    ('Emeritus of Woe', 4, 'creature', 0, 0, ['creature']),
    ('Harbinger of the Seas', 3, 'creature', 0, 0, ['creature']),
    ('Hokori, Dust Drinker', 4, 'creature', 0, 0, ['creature']),
    ('Icetill Explorer', 4, 'creature', 0, 0, ['creature']),
    ('Keldon Firebombers', 5, 'creature', 0, 0, ['creature', 'mass']),
    ('Lumra, Bellow of the Woods', 6, 'creature', 0, 0, ['creature']),
    ('Oracle of Mul Daya', 4, 'creature', 0, 0, ['creature']),
    ('Summon: Titan', 5, 'creature', 0, 0, ['creature', 'draw']),
    ('Boil', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Growth Spiral', 2, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ("Prishe's Wanderings", 3, 'spell', 0, 0, ['spell', 'ramp', 'is']),
    ('Sunder', 5, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Acid Rain', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Armageddon', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Bend or Break', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Boom // Bust', 2, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Cataclysm', 4, 'spell', 0, 0, ['spell', 'is']),
    ('Catastrophe', 6, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Cleansing', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Cleansing Nova', 5, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Death Cloud', 4, 'spell', 0, 0, ['spell', 'is']),
    ('Decree of Annihilation', 10, 'spell', 0, 0, ['spell', 'draw', 'mass', 'is']),
    ('Demonic Tutor', 2, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Devastation', 7, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Diabolic Tutor', 4, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Global Ruin', 5, 'spell', 0, 0, ['spell', 'is']),
    ('Grim Tutor', 3, 'spell', 0, 0, ['spell', 'tutor', 'is']),
    ('Jokulhaups', 6, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Obliterate', 8, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Ravages of War', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Reach the Horizon', 4, 'spell', 0, 0, ['spell', 'is']),
    ('Reanimate', 1, 'spell', 0, 0, ['spell', 'is']),
    ('Ruination', 4, 'spell', 0, 0, ['spell', 'mass', 'is']),
    ('Sinkhole', 2, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Solemn Offering', 3, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Splendid Reclamation', 4, 'spell', 0, 0, ['spell', 'is']),
    ('Stone Rain', 3, 'spell', 0, 0, ['spell', 'removal', 'is']),
    ('Tectonic Break', 3, 'spell', 0, 0, ['spell', 'is']),
    ('Thoughts of Ruin', 4, 'spell', 0, 0, ['spell', 'is']),
    ('Travel the Overworld', 7, 'spell', 0, 0, ['spell', 'draw', 'is']),
    ('Wildfire', 6, 'spell', 0, 0, ['spell', 'is']),
    ('Arcane Signet', 2, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Chromatic Lantern', 3, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Conduit of Worlds', 4, 'spell', 0, 0, ['spell']),
    ('Crucible of Worlds', 3, 'spell', 0, 0, ['spell']),
    ('Dingus Egg', 4, 'spell', 0, 0, ['spell']),
    ('Smokestack', 4, 'spell', 0, 0, ['spell']),
    ('Sol Ring', 1, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Static Orb', 3, 'spell', 0, 0, ['spell']),
    ('Timeless Lotus', 5, 'spell', 0, 0, ['spell', 'rock', 'ramp']),
    ('Winter Moon', 2, 'spell', 0, 0, ['spell']),
    ('Winter Orb', 2, 'spell', 0, 0, ['spell']),
    ('Choke', 3, 'spell', 0, 0, ['spell']),
    ('Curse of Marit Lage', 5, 'spell', 0, 0, ['spell']),
    ('Exploration', 1, 'spell', 0, 0, ['spell']),
    ('Fall of the Thran', 6, 'spell', 0, 0, ['spell', 'draw', 'mass']),
    ('Humility', 4, 'spell', 0, 0, ['spell']),
    ('Impending Disaster', 2, 'spell', 0, 0, ['spell', 'mass']),
    ('Mana Breach', 3, 'spell', 0, 0, ['spell']),
    ('Mana Vortex', 3, 'spell', 0, 0, ['spell']),
    ('Nether Void', 4, 'spell', 0, 0, ['spell']),
    ('Price of Glory', 3, 'spell', 0, 0, ['spell']),
    ('Rising Waters', 4, 'spell', 0, 0, ['spell']),
    ('Undergrowth Recon', 3, 'spell', 0, 0, ['spell']),
    ("Adventurer's Inn", 0, 'land', 0, 0, ['land', 'manaland']),
    ('Ba Sing Se', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Balamb Garden, SeeD Academy', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Baron, Airship Kingdom', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Capital City', 0, 'land', 0, 0, ['land', 'manaland', 'draw']),
    ('Cascading Cataracts', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Crossroads Village', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Darkmoss Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Darksteel Citadel', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Drossforge Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Eden, Seat of the Sanctum', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Gohn, Town of Ruin', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Goldmire Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Gongaga, Reactor Town', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Guadosalam, Farplane Gateway', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Insomnia, Crown City', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Ishgard, the Holy See', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Mistvault Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Rabanastre, Royal City', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Razortide Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Rustvale Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Sharlayan, Nation of Scholars', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Silverbluff Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Slagwoods Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Starting Town', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Tanglepool Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('The Gold Saucer', 0, 'land', 0, 0, ['land', 'manaland', 'draw', 'token']),
    ('Thornglint Bridge', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Treno, Dark City', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Vector, Imperial Capital', 0, 'land', 0, 0, ['land', 'manaland']),
    ('Windurst, Federation Center', 0, 'land', 0, 0, ['land', 'manaland']),
]
